src/print_result/easter/easter.c File Reference
#include `print_result/easter/easter.h`
Functions
static int a (int year)
static int b (int year)
static int c (int year)
static int m (int year)
static int n (int year)
static int d (int year)
static int e (int year)
static bool year_min_ten (int year)
static bool easter_nineteen (int year)
static bool easter_twentyfive (int year)
int day (int year)
char * month (int year)
Function Documentation
a()
static int a (int year) [static]
Definition at line 10 of file easter.c.
References NINETEEN.
Referenced by d(), and easter_twentyfive().
b()
static int b (int year) [static]
Definition at line 14 of file easter.c.
References FOUR.
Referenced by e().
c()
static int c (int year) [static]
Definition at line 18 of file easter.c.
References SEVEN.
Referenced by e().
d()
static int d (int year) [static]
Definition at line 39 of file easter.c.
References a(), m(), NINETEEN, and THIRTY.
Referenced by day(), e(), easter_nineteen(), easter_twentyfive(), month(), and year_min_ten().
day()
int day (int year)
Calcola il giorno del mese in cui cade la Pasqua
Precondition
l'anno deve essere compre tra il 1583 e il 2499
Parameters
year
Returns
Definition at line 59 of file easter.c.
References d(), e(), easter_nineteen(), easter_twentyfive(), is_valid_year(), NINE, NINETEEN, TWENTYFIVE, TWENTYTWO, and year_min_ten().
Referenced by is_april_easter(), print_april_easter(), and print_march_easter().
e()
static int e (int year) [static]
Definition at line 43 of file easter.c.
References b(), c(), d(), FOUR, n(), SEVEN, SIX, and TWO.
Referenced by day(), easter_nineteen(), easter_twentyfive(), month(), and year_min_ten().
easter_nineteen()
static bool easter_nineteen (int year) [static]
Definition at line 51 of file easter.c.
References d(), e(), NINE, and TWENTYSIX.
Referenced by day().
easter_twentyfive()
static bool easter_twentyfive (int year) [static]
Definition at line 55 of file easter.c.
References a(), d(), e(), NINE, SIX, TEN, TWENTYEIGHT, and TWENTYSIX.
Referenced by day().
m()
static int m (int year) [static]
Definition at line 22 of file easter.c.
References MIN_YEAR, ONE, TWENTYFIVE, TWENTYFOUR, TWENTYSIX, TWENTYTHREE, TWENTYTWO, YEAR_A, YEAR_B, YEAR_C, YEAR_D, and YEAR_E.
Referenced by d().
month()
char* month (int year)
Calcola il mese in cui cade la Pasqua
Precondition
l'anno deve essere compre tra il 1583 e il 2499
Parameters
year
Returns
Definition at line 66 of file easter.c.
References APRIL, d(), e(), is_valid_year(), MARCH, and TEN.
Referenced by is_april_easter(), print_april_easter(), and print_march_easter().
n()
static int n (int year) [static]
Definition at line 30 of file easter.c.
References FIVE, FOUR, MAX_YEAR, MIN_YEAR, ONE, SIX, THREE, TWO, YEAR_A, YEAR_B, YEAR_C, YEAR_D, YEAR_F, YEAR_G, and ZERO.
Referenced by e().
year_min_ten()
static bool year_min_ten (int year) [static]
Definition at line 47 of file easter.c.
References d(), e(), and TEN.
Referenced by day().