src/print_result/is_valid/is_valid.c File Reference
#include `is_valid.h`
Functions
bool is_valid_year (int year)
Function Documentation
is_valid_year()
bool is_valid_year (int year)
Verifica che l'anno di cui calcolare la Pasqua sia compreso tra il 1583 e il 2499
Parameters
year
Returns
Definition at line 10 of file is_valid.c.
References MAX_YEAR, and MIN_YEAR.
Referenced by day(), month(), and print_easter().