src/print_result/is_valid/is_valid.h File Reference
#include <stdbool.h>
Macros
#define MIN_YEAR 1583
#define MAX_YEAR 2499
Functions
bool is_valid_year (int year)
Macro Definition Documentation
MAX_YEAR
#define MAX_YEAR 2499
Definition at line 14 of file is_valid.h.
MIN_YEAR
#define MIN_YEAR 1583
Definition at line 13 of file is_valid.h.
Function Documentation
is_valid_year()
bool is_valid_year (int year)
Verifica che l'anno di cui calcolare la Pasqua sia compreso tra il 1583 e il 2499
Parameters
year
Returns
Definition at line 10 of file is_valid.c.
References MAX_YEAR, and MIN_YEAR.
Referenced by day(), month(), and print_easter().