src/print_result/print_easter.c File Reference
#include `print_result/print_easter.h`
Functions
static void print_april_easter (int year)
static void print_march_easter (int year)
static bool is_april_easter (int year)
static void print_valid_data (int year)
static void print_not_valid_data ()
void print_easter (int year)
Function Documentation
is_april_easter()
static bool is_april_easter (int year) [static]
Definition at line 18 of file print_easter.c.
References APRIL, day(), month(), TEN, and ZERO.
Referenced by print_valid_data().
print_april_easter()
static void print_april_easter (int year) [static]
Definition at line 10 of file print_easter.c.
References BAR, DATE, day(), and month().
Referenced by print_valid_data().
print_easter()
void print_easter (int year)
Stampa la data della Pasqua
Parameters
year
Definition at line 30 of file print_easter.c.
References is_valid_year(), print_not_valid_data(), and print_valid_data().
print_march_easter()
static void print_march_easter (int year) [static]
Definition at line 14 of file print_easter.c.
References BAR1, DATE, day(), and month().
Referenced by print_valid_data().
print_not_valid_data()
static void print_not_valid_data () [static]
Definition at line 26 of file print_easter.c.
References NOT_VALID_YEAR.
Referenced by print_easter().
print_valid_data()
static void print_valid_data (int year) [static]
Definition at line 22 of file print_easter.c.
References is_april_easter(), print_april_easter(), and print_march_easter().
Referenced by print_easter().