src/print_result/print_easter.h File Reference
#include `print_result/easter/easter.h`
#include `is_valid/is_valid.h`
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
Macros
#define DATE `Data della Santa Pasqua: %d %s`
#define BAR `\n==================================\n`
#define BAR1 `\n=================================\n`
#define NOT_VALID_YEAR `\nL'anno inserito non e' valido`
Functions
void print_easter (int year)
Macro Definition Documentation
BAR
#define BAR `\n==================================\n`
Definition at line 19 of file print_easter.h.
Referenced by print_april_easter().
BAR1
#define BAR1 `\n=================================\n`
Definition at line 20 of file print_easter.h.
Referenced by print_march_easter().
DATE
#define DATE `Data della Santa Pasqua: %d %s`
Definition at line 18 of file print_easter.h.
Referenced by print_april_easter(), and print_march_easter().
NOT_VALID_YEAR
#define NOT_VALID_YEAR `\nL'anno inserito non e' valido`
Definition at line 21 of file print_easter.h.
Referenced by print_not_valid_data().
Function Documentation
print_easter()
void print_easter (int year)
Stampa la data della Pasqua
Parameters
year
Definition at line 30 of file print_easter.c.
References is_valid_year(), print_not_valid_data(), and print_valid_data().