src/repeat/repeat.c File Reference
#include `repeat.h`
*
Functions
static bool invalid_repeat (int repeat)
static int get_repeat (void)
bool repeat (void)
Variables
static const int ZERO = 0
static const int ONE = 1
static const int TWO = 2
static const char * REPEAT_STRING = `\n\nCalcolare la data di un'altra Pasqua?\n(1=si,2=no) `
static const char * SPEC_INT = `%d`
Function Documentation
static int get_repeat (void) [static]
Definition at line 20 of file repeat.c.
References invalid_repeat(), repeat(), REPEAT_STRING, SPEC_INT, and ZERO.
Referenced by repeat().
static bool invalid_repeat (int repeat) [static]
Definition at line 16 of file repeat.c.
References ONE, and TWO.
Referenced by get_repeat().
bool repeat (void)
Verifica l'intenzione dell'utente di calcolare un altro codice fiscale
Returns
Definition at line 29 of file repeat.c.
References get_repeat(), and ONE.
Referenced by get_repeat().
Variable Documentation
const int ONE = 1 [static]
Definition at line 11 of file repeat.c.
Referenced by invalid_repeat(), and repeat().
const char* REPEAT_STRING = `\n\nCalcolare la data di un'altra Pasqua?\n(1=si,2=no) ` [static]
Definition at line 13 of file repeat.c.
Referenced by get_repeat().
const char* SPEC_INT = `%d` [static]
Definition at line 14 of file repeat.c.
Referenced by get_repeat().
const int TWO = 2 [static]
Definition at line 12 of file repeat.c.
Referenced by invalid_repeat().
const int ZERO = 0 [static]
Definition at line 10 of file repeat.c.
Referenced by get_repeat().